version: '3.8'

services:
  web:
    build: .
    command: gunicorn droom_demo.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

